### ISSUE TITLE
After connecting to one MetaMask account, the plugin cannot connect to another MetaMask account

### ISSUE THREAD

**Issue by vsszhang** [PureStake/moonbeam-remix-plugin#6]
Hi, I have a question want to ask

# Problem Description
I use remix Moonbeam plugin connect one MetaMask Account, and successfully compile and deploy my contract. Then I want to switch another MetaMask account. After using MetaMask switch another account, I click 'connect' button in Remix but it still connect to the previous account. Even refreshing cannot make it.
So, is it a bug or what should I do to connect another MetaMask account successfully.🤔

# Date
question appeared on 2021/12/15

**Comment by joelamouche** [comment]
@vsszhang Thanks for the feedback. We will try to fix that asap. Did you try selecting the MetaMask account first and then refreshing?

**Comment by vsszhang** [comment]
@joelamouche Yes, I select My MetaMask account first.
My complete operation process is as follows：
Choosing one MetaMask account => Using plugin connect my MetaMask account => Compiling and deploying my contract => Selecting another MetaMask account => Refreshing web => Clicking the 'connect' button => Founding that the ACCOUNT not change
![Snipaste_2021-12-15_17-21-25](https://user-images.githubusercontent.com/71303553/146159638-07085288-c326-4489-b80a-904610750783.jpg)

**Comment by ioannist** [comment]
same problem here; tried multiple tricks to get it to change account but it is a very stubborn field it seems...

**Comment by albertov19** [comment]
So @ioannist after a little bit of research the main problem is that plugins are i-frames on top of the Remix website. Therefore, even though Metamask shows as connected, it is actually connected to the Remix website and not the i-frame plugin "website".

The only solution I've found so far, is to go to the account that is connected in the plugin and click in the three dots -> connected sites -> search for `https://purestake.github.io` and remove it. Once you reload the plugin and click connect in the account, authorize all relevant accounts and you should be able to switch between them.

@eshaben we can probably think about doing a button to manually connect each active account? Or to disconnect accounts, not sure.

**Comment by ioannist** [comment]
I've tried that, problem is I don't see purestake.github.io even immediately after I authorize connection to it

![image](https://user-images.githubusercontent.com/6544125/191480821-3adaf487-a29e-4028-9c75-7c232bef17dc.png)

**Comment by ioannist** [comment]
and even after I click on Connect button, and authorize connection (again)

![image](https://user-images.githubusercontent.com/6544125/191481346-c7e17e4d-51ec-4690-8980-8e526e938627.png)

**Comment by albertov19** [comment]
@ioannist I'm referring to this 
![image](https://user-images.githubusercontent.com/64150856/191481576-523a6a4d-eca3-4c6e-a0d6-09a1cd983697.png)

Find the account that is constantly connecting to the Plugin in Metamask, go there and manually remove `https://purestake.github.io`

**Comment by ioannist** [comment]
Alright, found it, you have to select the account that is connected to see the connected networks (duh!!)

**Comment by ioannist** [comment]
Why is it that I always find the answer 3 seconds before someone offers it to me on a plate... lol

**Comment by albertov19** [comment]
I've pushed a no so elegant fix that adds a `Connect` button to the `ACCOUNT` tab, which will request to revise permissions of Metamask Accounts. This will help with connecting different accounts without needing to disconnect all previously connected accounts.

I'll mark this close as the issue is more or less fix
